### PR TITLE
Allow log properties configurations 

### PR DESCRIPTION
**Pull request by dharmeshkakadia**
Adding log properties configurations so that user can control the logging level of presto.

### CODE REVIEW

**Review by kokosing — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please squash the commits and update REDME file. Other than that it looks good!

**Comment by anusudarsan** [comment]
Looks good mod updating README. Once you are done, please squash the commits. Thanks.

**Comment by dharmeshkakadia** [comment]
This closes #47

**Comment by kokosing** [comment]
@dharmeshkakadia Merged. Thank you for contribution!

**Comment by dharmeshkakadia** [comment]
Thanks everyone !

**Pull request merged**
